#  Importing Data From API

In [21]:
import requests
import pandas as pd
import statistics as stat

In [49]:
URL = "https://api.collegefootballdata.com/rankings/"
years = range(2015, 2019)

rankings = {
    "Year": [],
    "Season": [],
    "Week": [],
    "Ranking": [],
    "College": [],
}

for y in years:
    for i in range(1,16):
        PARAMS = {
            'year': y,
            'week': i,
            'seasonType': 'regular'
        }
        
        data = requests.get(url = URL, params=PARAMS).json()
        
        if len(data) > 0:
            ranks = data[0]["polls"][0]["ranks"]
            for r in ranks:
                rankings["Year"].append(y)
                rankings["Week"].append(i)
                rankings["College"].append(r["school"])
                rankings["Ranking"].append(r["rank"])

In [50]:
for y in rankings["Year"]:
    rankings["Season"].append(str(y)+"-"+str(y+1-2000))

In [55]:
df = pd.DataFrame(rankings).drop_duplicates().sort_values(by=["Year", "Week", "Ranking"])
df

      Year   Season  Week  Ranking            College
22    2015  2015-16     1        1         Ohio State
19    2015  2015-16     1        2                TCU
3     2015  2015-16     1        3            Alabama
11    2015  2015-16     1        4             Baylor
13    2015  2015-16     1        5             Oregon
23    2015  2015-16     1        6     Michigan State
6     2015  2015-16     1        7             Auburn
8     2015  2015-16     1        8      Florida State
1     2015  2015-16     1        9            Georgia
15    2015  2015-16     1       10                USC
0     2015  2015-16     1       11         Notre Dame
9     2015  2015-16     1       12            Clemson
7     2015  2015-16     1       13                LSU
16    2015  2015-16     1       14               UCLA
4     2015  2015-16     1       15           Ole Miss
17    2015  2015-16     1       16      Arizona State
10    2015  2015-16     1       17       Georgia Tech
24    2015  2015-16     1       18          Wisconsin
12    2015  2015-16     1       19           Oklahoma
5     2015  2015-16     1       20           Arkansas
14    2015  2015-16     1       21           Stanford
18    2015  2015-16     1       22            Arizona
20    2015  2015-16     1       23           Missouri
21    2015  2015-16     1       24        Boise State
2     2015  2015-16     1       25          Tennessee
47    2015  2015-16     2        1         Ohio State
28    2015  2015-16     2        2            Alabama
43    2015  2015-16     2        3                TCU
36    2015  2015-16     2        4             Baylor
38    2015  2015-16     2        5             Oregon
...    ...      ...   ...      ...                ...
1471  2018  2018-19    14       21       Northwestern
1472  2018  2018-19    14       22        Boise State
1473  2018  2018-19    14       23         Iowa State
1474  2018  2018-19    14       24           Missouri
1475  2018  2018-19    14       25       Fresno State
1476  2018  2018-19    15        1            Alabama
1477  2018  2018-19    15        2            Clemson
1478  2018  2018-19    15        3         Notre Dame
1479  2018  2018-19    15        4           Oklahoma
1480  2018  2018-19    15        5            Georgia
1481  2018  2018-19    15        6         Ohio State
1482  2018  2018-19    15        7           Michigan
1483  2018  2018-19    15        8                UCF
1484  2018  2018-19    15        9         Washington
1485  2018  2018-19    15       10            Florida
1486  2018  2018-19    15       11                LSU
1487  2018  2018-19    15       12         Penn State
1488  2018  2018-19    15       13   Washington State
1489  2018  2018-19    15       14           Kentucky
1490  2018  2018-19    15       15              Texas
1491  2018  2018-19    15       16      West Virginia
1492  2018  2018-19    15       17               Utah
1493  2018  2018-19    15       18  Mississippi State
1494  2018  2018-19    15       19          Texas A&M
1495  2018  2018-19    15       20           Syracuse
1496  2018  2018-19    15       21       Fresno State
1497  2018  2018-19    15       22       Northwestern
1498  2018  2018-19    15       23           Missouri
1499  2018  2018-19    15       24         Iowa State
1500  2018  2018-19    15       25        Boise State

[1501 rows x 5 columns]

In [52]:
df.to_csv("df.csv", index=False)

# Finding Season Average Rank

In [56]:
season_rankings = df.groupby(["Year", "College"]).mean()
season_rankings

                             Week    Ranking
Year College
2015 Alabama             8.000000   5.733333
     Arizona             2.500000  19.250000
     Arizona State       1.000000  16.000000
     Arkansas            1.500000  19.000000
     Auburn              2.500000  13.500000
     BYU                 3.000000  22.000000
     Baylor              8.000000   5.466667
     Boise State         4.000000  22.500000
     California          6.500000  22.000000
     Clemson             8.000000   5.933333
     Duke                8.000000  21.000000
     Florida            10.000000  13.181818
     Florida State       8.000000  10.600000
     Georgia             4.750000  12.750000
     Georgia Tech        2.500000  17.250000
     Houston            11.500000  18.250000
     Iowa               10.500000  10.000000
     LSU                 7.642857  10.785714
     Memphis             8.500000  20.166667
     Michigan           10.500000  15.900000
     Michigan State      8.000000   5.333333
     Mississippi State  10.200000  22.800000
     Missouri            2.500000  21.750000
     Navy               13.000000  20.000000
     North Carolina     12.500000  13.166667
     Northwestern        9.000000  18.300000
     Notre Dame          8.000000   9.066667
     Ohio State          8.000000   2.266667
     Oklahoma            8.000000  12.066667
     Oklahoma State      9.000000  13.923077
...                           ...        ...
2018 Michigan State      3.500000  18.166667
     Mississippi State   8.181818  18.181818
     Missouri           14.500000  23.500000
     NC State            8.200000  20.600000
     Northwestern       14.000000  21.333333
     Notre Dame          8.000000   5.333333
     Ohio State          8.000000   5.400000
     Oklahoma            8.000000   6.200000
     Oklahoma State      3.500000  20.666667
     Oregon              6.000000  18.428571
     Penn State          8.000000  12.266667
     Pittsburgh         13.000000  25.000000
     South Carolina      2.000000  24.000000
     South Florida       8.000000  21.000000
     Stanford            5.000000  14.444444
     Syracuse           12.500000  18.000000
     TCU                 2.500000  15.750000
     Texas               9.250000  15.000000
     Texas A&M           9.500000  19.500000
     UAB                12.000000  25.000000
     UCF                 8.000000  12.666667
     USC                 2.000000  16.000000
     Utah               12.000000  19.142857
     Utah State         11.500000  16.000000
     Virginia           10.000000  22.000000
     Virginia Tech       3.500000  16.500000
     Washington          8.000000  12.400000
     Washington State   11.500000  12.500000
     West Virginia       8.000000  12.333333
     Wisconsin           5.000000  12.000000

[183 rows x 2 columns]

In [57]:
season_rankings_ungrouped = season_rankings.reset_index()
season_rankings_ungrouped

season_rankings_ungrouped = season_rankings_ungrouped.rename(columns={"Ranking": "SeasonRanking"})[["Year",
                                                                                                     "College",
                                                                                                     "SeasonRanking"]]
season_rankings_ungrouped

     Year            College  SeasonRanking
0    2015            Alabama       5.733333
1    2015            Arizona      19.250000
2    2015      Arizona State      16.000000
3    2015           Arkansas      19.000000
4    2015             Auburn      13.500000
5    2015                BYU      22.000000
6    2015             Baylor       5.466667
7    2015        Boise State      22.500000
8    2015         California      22.000000
9    2015            Clemson       5.933333
10   2015               Duke      21.000000
11   2015            Florida      13.181818
12   2015      Florida State      10.600000
13   2015            Georgia      12.750000
14   2015       Georgia Tech      17.250000
15   2015            Houston      18.250000
16   2015               Iowa      10.000000
17   2015                LSU      10.785714
18   2015            Memphis      20.166667
19   2015           Michigan      15.900000
20   2015     Michigan State       5.333333
21   2015  Mississippi State      22.800000
22   2015           Missouri      21.750000
23   2015               Navy      20.000000
24   2015     North Carolina      13.166667
25   2015       Northwestern      18.300000
26   2015         Notre Dame       9.066667
27   2015         Ohio State       2.266667
28   2015           Oklahoma      12.066667
29   2015     Oklahoma State      13.923077
..    ...                ...            ...
153  2018     Michigan State      18.166667
154  2018  Mississippi State      18.181818
155  2018           Missouri      23.500000
156  2018           NC State      20.600000
157  2018       Northwestern      21.333333
158  2018         Notre Dame       5.333333
159  2018         Ohio State       5.400000
160  2018           Oklahoma       6.200000
161  2018     Oklahoma State      20.666667
162  2018             Oregon      18.428571
163  2018         Penn State      12.266667
164  2018         Pittsburgh      25.000000
165  2018     South Carolina      24.000000
166  2018      South Florida      21.000000
167  2018           Stanford      14.444444
168  2018           Syracuse      18.000000
169  2018                TCU      15.750000
170  2018              Texas      15.000000
171  2018          Texas A&M      19.500000
172  2018                UAB      25.000000
173  2018                UCF      12.666667
174  2018                USC      16.000000
175  2018               Utah      19.142857
176  2018         Utah State      16.000000
177  2018           Virginia      22.000000
178  2018      Virginia Tech      16.500000
179  2018         Washington      12.400000
180  2018   Washington State      12.500000
181  2018      West Virginia      12.333333
182  2018          Wisconsin      12.000000

[183 rows x 3 columns]

In [58]:
avg_merged = pd.merge(
    left=df, right=season_rankings_ungrouped, how='left', left_on=['Year', 'College'], right_on=['Year', 'College']
)
df = avg_merged.drop_duplicates()
df

      Year   Season  Week  Ranking            College  SeasonRanking
0     2015  2015-16     1        1         Ohio State       2.266667
1     2015  2015-16     1        2                TCU       5.866667
2     2015  2015-16     1        3            Alabama       5.733333
3     2015  2015-16     1        4             Baylor       5.466667
4     2015  2015-16     1        5             Oregon      14.555556
5     2015  2015-16     1        6     Michigan State       5.333333
6     2015  2015-16     1        7             Auburn      13.500000
7     2015  2015-16     1        8      Florida State      10.600000
8     2015  2015-16     1        9            Georgia      12.750000
9     2015  2015-16     1       10                USC      16.777778
10    2015  2015-16     1       11         Notre Dame       9.066667
11    2015  2015-16     1       12            Clemson       5.933333
12    2015  2015-16     1       13                LSU      10.785714
13    2015  2015-16     1       14               UCLA      16.909091
14    2015  2015-16     1       15           Ole Miss      15.071429
15    2015  2015-16     1       16      Arizona State      16.000000
16    2015  2015-16     1       17       Georgia Tech      17.250000
17    2015  2015-16     1       18          Wisconsin      21.375000
18    2015  2015-16     1       19           Oklahoma      12.066667
19    2015  2015-16     1       20           Arkansas      19.000000
20    2015  2015-16     1       21           Stanford      13.307692
21    2015  2015-16     1       22            Arizona      19.250000
22    2015  2015-16     1       23           Missouri      21.750000
23    2015  2015-16     1       24        Boise State      22.500000
24    2015  2015-16     1       25          Tennessee      23.666667
25    2015  2015-16     2        1         Ohio State       2.266667
26    2015  2015-16     2        2            Alabama       5.733333
27    2015  2015-16     2        3                TCU       5.866667
28    2015  2015-16     2        4             Baylor       5.466667
29    2015  2015-16     2        5             Oregon      14.555556
...    ...      ...   ...      ...                ...            ...
1471  2018  2018-19    14       21       Northwestern      21.333333
1472  2018  2018-19    14       22        Boise State      22.400000
1473  2018  2018-19    14       23         Iowa State      22.500000
1474  2018  2018-19    14       24           Missouri      23.500000
1475  2018  2018-19    14       25       Fresno State      21.800000
1476  2018  2018-19    15        1            Alabama       1.000000
1477  2018  2018-19    15        2            Clemson       2.333333
1478  2018  2018-19    15        3         Notre Dame       5.333333
1479  2018  2018-19    15        4           Oklahoma       6.200000
1480  2018  2018-19    15        5            Georgia       4.066667
1481  2018  2018-19    15        6         Ohio State       5.400000
1482  2018  2018-19    15        7           Michigan      11.066667
1483  2018  2018-19    15        8                UCF      12.666667
1484  2018  2018-19    15        9         Washington      12.400000
1485  2018  2018-19    15       10            Florida      14.700000
1486  2018  2018-19    15       11                LSU       9.600000
1487  2018  2018-19    15       12         Penn State      12.266667
1488  2018  2018-19    15       13   Washington State      12.500000
1489  2018  2018-19    15       14           Kentucky      15.909091
1490  2018  2018-19    15       15              Texas      15.000000
1491  2018  2018-19    15       16      West Virginia      12.333333
1492  2018  2018-19    15       17               Utah      19.142857
1493  2018  2018-19    15       18  Mississippi State      18.181818
1494  2018  2018-19    15       19          Texas A&M      19.500000
1495  2018  2018-19    15       20           Syracuse      18.000000
1496  2018  2018-19    15       21       Fresno State      21.800000
1497  2018  2018-19    15       22       Northwestern      21.333333
1498  2018  2018-19    15       23           Missouri      23.500000
1499  2018  2018-19    15       24         Iowa State      22.500000
1500  2018  2018-19    15       25        Boise State      22.400000

[1501 rows x 6 columns]

# Merging Data into Main Dataset

In [59]:
game_data = pd.read_csv('game_data.csv')
del game_data['Unnamed: 0']
game_data

,School,Opponent,Date,Season,AtHome,NeutralLocation,Score,OppScore,Total,Outcome,...,XPM,XPA,XPPercent,FGM,FGA,FGPercent,KickPts,Fum,Int,TotalTO
0,Georgia State,Charlotte,2015-09-04,2015-16,1,0,20,23,43,L,...,2,2,100.0,2,3,66.7,8,2,1,3
1,Oregon State,Weber State,2015-09-04,2015-16,1,0,26,7,33,W,...,2,2,100.0,4,4,100.0,14,0,1,1
2,Syracuse,Rhode Island,2015-09-04,2015-16,1,0,47,0,47,W,...,6,6,100.0,1,2,50.0,9,0,1,1
3,Western Michigan,Michigan State,2015-09-04,2015-16,1,0,24,37,61,L,...,3,3,100.0,1,2,50.0,6,0,2,2
4,Central Michigan,Oklahoma State,2015-09-03,2015-16,1,0,13,24,37,L,...,1,1,100.0,2,2,100.0,7,0,1,1
5,Fresno State,Abilene Christian,2015-09-03,2015-16,1,0,34,13,47,W,...,4,4,100.0,2,3,66.7,10,1,2,3
6,Hawaii,Colorado,2015-09-03,2015-16,1,0,28,20,48,W,...,2,2,100.0,2,2,100.0,8,0,2,2
7,Idaho,Ohio,2015-09-03,2015-16,1,0,28,45,73,L,...,2,2,100.0,2,2,100.0,8,1,2,3
8,Minnesota,Texas Christian,2015-09-03,2015-16,1,0,17,23,40,L,...,2,2,100.0,1,1,100.0,5,2,0,2
9,San Jose State,New Hampshire,2015-09-03,2015-16,1,0,43,13,56,W,...,4,6,66.7,1,2,50.0,7,0,0,0
10,Central Florida,Florida International,2015-09-03,2015-16,1,0,14,15,29,L,...,2,2,100.0,0,1,0.0,2,0,0,0
11,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,3,3,100.0,1,3,33.3,6,0,1,1
12,Utah State,Southern Utah,2015-09-03,2015-16,1,0,12,9,21,W,...,1,1,100.0,1,1,100.0,4,0,1,1
13,Wake Forest,Elon,2015-09-03,2015-16,1,0,41,3,44,W,...,5,5,100.0,2,3,66.7,11,0,0,0
14,West Virginia,Liberty,2015-09-12,2015-16,1,0,41,17,58,W,...,5,5,100.0,2,3,66.7,11,0,0,0
15,Wisconsin,Miami (OH),2015-09-12,2015-16,1,0,58,0,58,W,...,7,7,100.0,3,3,100.0,16,0,1,1
16,Wyoming,Eastern Michigan,2015-09-12,2015-16,1,0,29,48,77,L,...,3,3,100.0,0,2,0.0,3,1,0,1
17,Florida Atlantic,Miami (FL),2015-09-11,2015-16,1,0,20,44,64,L,...,2,2,100.0,2,3,66.7,8,3,2,5
18,Utah,Utah State,2015-09-11,2015-16,1,0,24,14,38,W,...,3,3,100.0,1,1,100.0,6,0,0,0
19,Western Kentucky,Louisiana Tech,2015-09-10,2015-16,1,0,41,38,79,W,...,3,3,100.0,4,4,100.0,15,1,0,1
20,Virginia Tech,Ohio State,2015-09-07,2015-16,1,0,24,42,66,L,...,3,3,100.0,1,2,50.0,6,1,1,2
21,Marshall,Purdue,2015-09-06,2015-16,1,0,41,31,72,W,...,5,5,100.0,2,2,100.0,11,2,1,3
22,Air Force,Morgan State,2015-09-05,2015-16,1,0,63,7,70,W,...,9,9,100.0,0,1,0.0,9,0,0,0
23,Arkansas,Texas-El Paso,2015-09-05,2015-16,1,0,48,13,61,W,...,6,6,100.0,2,2,100.0,12,0,0,0
24,Boston College,Maine,2015-09-05,2015-16,1,0,24,3,27,W,...,3,3,100.0,1,2,50.0,6,0,0,0
25,Buffalo,Albany,2015-09-05,2015-16,1,0,51,14,65,W,...,6,7,85.7,1,1,100.0,9,0,0,0
26,California,Grambling State,2015-09-05,2015-16,1,0,73,14,87,W,...,10,10,100.0,1,1,100.0,13,1,2,3
27,Cincinnati,Alabama A&M,2015-09-05,2015-16,1,0,52,10,62,W,...,7,7,100.0,1,1,100.0,10,2,0,2
28,Colorado State,Savannah State,2015-09-05,2015-16,1,0,65,13,78,W,...,8,9,88.9,1,2,50.0,11,4,1,5
29,East Carolina,Towson,2015-09-05,2015-16,1,0,28,20,48,W,...,4,4,100.0,0,1,0.0,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5174,Ball State,Eastern Michigan,2019-10-12,2019-20,0,0,29,23,52,W,...,3,3,100.0,0,1,0.0,3,1,0,1
5175,Brigham Young,South Florida,2019-10-12,2019-20,0,0,23,27,50,L,...,2,2,100.0,3,4,75.0,11,1,0,1
5176,Charlotte,Florida International,2019-10-12,2019-20,0,0,23,48,71,L,...,2,3,66.7,1,1,100.0,5,1,0,1
5177,Cincinnati,Houston,2019-10-12,2019-20,0,0,38,23,61,W,...,5,5,100.0,1,2,50.0,8,0,1,1
5178,Fresno State,Air Force,2019-10-12,2019-20,0,0,24,43,67,L,...,3,3,100.0,1,1,100.0,6,0,1,1
5179,Georgia State,Coastal Carolina,2019-10-12,2019-20,0,0,31,21,52,W,...,4,4,100.0,1,2,50.0,7,0,1,1
5180,Georgia Tech,Duke,2019-10-12,2019-20,0,0,23,41,64,L,...,2,2,100.0,1,1,100.0,5,0,0,0
5181,Iowa State,West Virginia,2019-10-12,2019-20,0,0,38,14,52,W,...,5,5,100.0,1,1,100.0,8,0,1,1
5182,Kent State,Akron,2019-10-12,2019-20,0,0,26,3,29,W,...,2,2,100.0,4,4,100.0,14,0,0,0
5183,Louisville,Wake Forest,2019-10-12,2019-20,0,0,62,59,121,W,...,8,8,100.0,2,2,100.0,14,1,1,2
5184,Miami (OH),Western Michigan,2019-10-12,2019-20,0,0,16,38,54,L,...,1,1,100.0,3,4,75.0,10,0,3,3
5185,Michigan,Illinois,2019-10-12,2019-20,0,0,42,25,67,W,...,6,6,100.0,0,1,0.0,6,2,0,2
5186,Middle Tennessee State,Florida Atlantic,2019-10-12,2019-20,0,0,13,28,41,L,...,1,2,50.0,0,1,0.0,1,0,3,3
5187,Mississippi State,Tennessee,2019-10-12,2019-20,0,0,10,20,30,L,...,1,1,100.0,1,2,50.0,4,0,3,3
5188,Navy,Tulsa,2019-10-12,2019-20,0,0,45,17,62,W,...,6,6,100.0,1,1,100.0,9,1,0,1
5189,North Texas,Southern Mississippi,2019-10-12,2019-20,0,0,27,45,72,L,...,3,4,75.0,0,1,0.0,3,0,2,2
5190,Northern Illinois,Ohio,2019-10-12,2019-20,0,0,39,36,75,W,...,3,3,100.0,2,4,50.0,9,0,1,1
5191,Oklahoma,Texas,2019-10-12,2019-20,0,1,34,27,61,W,...,4,4,100.0,2,2,100.0,10,1,1,2
5192,Old Dominion,Marshall,2019-10-12,2019-20,0,0,17,31,48,L,...,2,2,100.0,1,1,100.0,5,0,0,0
5193,Penn State,Iowa,2019-10-12,2019-20,0,0,17,12,29,W,...,2,2,100.0,1,1,100.0,5,0,0,0
5194,San Jose State,Nevada,2019-10-12,2019-20,0,0,38,41,79,L,...,5,5,100.0,1,1,100.0,8,1,1,2
5195,South Carolina,Georgia,2019-10-12,2019-20,0,0,20,17,37,W,...,2,2,100.0,2,4,50.0,8,0,0,0
5196,Texas Tech,Baylor,2019-10-12,2019-20,0,0,30,33,63,L,...,3,3,100.0,3,3,100.0,12,1,2,3
5197,Toledo,Bowling Green State,2019-10-12,2019-20,0,0,7,20,27,L,...,1,1,100.0,0,2,0.0,1,1,1,2
5198,Alabama-Birmingham,Texas-San Antonio,2019-10-12,2019-20,0,0,33,14,47,W,...,3,3,100.0,4,4,100.0,15,1,1,2
5199,Nevada-Las Vegas,Vanderbilt,2019-10-12,2019-20,0,0,34,10,44,W,...,4,4,100.0,2,2,100.0,10,1,0,1
5200,Southern California,Notre Dame,2019-10-12,2019-20,0,0,27,30,57,L,...,3,3,100.0,2,2,100.0,9,0,0,0
5201,Utah,Oregon State,2019-10-12,2019-20,0,0,52,7,59,W,...,7,7,100.0,1,1,100.0,10,1,0,1
5202,Washington,Arizona,2019-10-12,2019-20,0,0,51,27,78,W,...,6,6,100.0,3,3,100.0,15,1,0,1
5203,Washington State,Arizona State,2019-10-12,2019-20,0,0,34,38,72,L,...,4,4,100.0,2,2,100.0,10,0,0,0

### Replace Differently Named Schools

In [60]:
def check_names(dataset):
    bad_names = []
    for w in dataset["College"]:
        if w not in game_data["School"].values and w not in game_data["Opponent"].values and w not in bad_names:
            bad_names.append(w)
    print(len(bad_names))
    print(bad_names)

In [61]:
df_fix_names = df
df_fix_names = df_fix_names.replace('Ohio State', 'Ohio')
df_fix_names = df_fix_names.replace('LSU', 'Louisiana State')
df_fix_names = df_fix_names.replace('Ole Miss', 'Mississippi')
df_fix_names = df_fix_names.replace('Pitt', 'Pittsburgh')
df_fix_names = df_fix_names.replace('SMU', 'Southern Methodist')
df_fix_names = df_fix_names.replace('UAB', 'Alabama-Birmingham')
df_fix_names = df_fix_names.replace('UCF', 'Central Florida')
df_fix_names = df_fix_names.replace('UCF', 'Central Florida')
df_fix_names = df_fix_names.replace('UNLV', 'Nevada-Las Vegas')
df_fix_names = df_fix_names.replace('USC', 'Southern California')
df_fix_names = df_fix_names.replace('UTEP', 'Texas-El Paso')
df_fix_names = df_fix_names.replace('UTSA', 'TExas-San Antonio')
df_fix_names = df_fix_names.replace("Mississippi St", "Mississippi State")
df_fix_names = df_fix_names.replace("LSU", "Louisiana State")
df_fix_names = df_fix_names.replace("Miami Florida", "Miami (FL)")
df_fix_names = df_fix_names.replace("NC State", "North Carolina State")
df_fix_names = df_fix_names.replace("Florida Intl", "Florida International")
df_fix_names = df_fix_names.replace("USC", "Southern California")
df_fix_names = df_fix_names.replace("TCU", "Texas Christian")
df_fix_names = df_fix_names.replace("UL Lafayette", "Lafayette")
df_fix_names = df_fix_names.replace("Appalachian St", "Appalachian State")
df_fix_names = df_fix_names.replace("SMU", "Southern Methodist")
df_fix_names = df_fix_names.replace("Bowling Green", "Bowling Green State")
df_fix_names = df_fix_names.replace("BYU", "Brigham Young")
df_fix_names = df_fix_names.replace("Miami Ohio", "Miami (OH)")
df_fix_names = df_fix_names.replace("Southern Miss", "Southern Mississippi")
df_fix_names = df_fix_names.replace("UNLV", "Nevada-Las Vegas")
df_fix_names = df_fix_names.replace("UTEP", "Texas-El Paso")
df_fix_names = df_fix_names.replace("UTSA", "Texas-San Antonio")
df_fix_names = df_fix_names.replace("Middle Tenn St", "Middle Tennessee State")
df_fix_names = df_fix_names.replace("Kent", "Kent State")
df_fix_names = df_fix_names.replace("Charlotte U", "Charlotte")
df_fix_names = df_fix_names.replace("UL Monroe", "Louisiana-Monroe")
df_fix_names = df_fix_names.replace("UAB", "Alabama-Birmingham")
df_fix_names = df_fix_names.replace("NW Missouri State", "Missouri State")
df_fix_names = df_fix_names.replace("Mary Hardin-Baylor", "Baylor")
df_fix_names = df_fix_names.replace("Texas A&M Commerce", "Texas A&M")
df_fix_names = df_fix_names.replace("McNeese St", "McNeese State")
df_fix_names = df_fix_names.replace("Tennessee Chat", "Chattanooga")
df_fix_names = df_fix_names.replace('Miami', 'Miami (FL)')
check_names(df_fix_names)

0
[]

In [62]:
df = df_fix_names
df

      Year   Season  Week  Ranking              College  SeasonRanking
0     2015  2015-16     1        1                 Ohio       2.266667
1     2015  2015-16     1        2      Texas Christian       5.866667
2     2015  2015-16     1        3              Alabama       5.733333
3     2015  2015-16     1        4               Baylor       5.466667
4     2015  2015-16     1        5               Oregon      14.555556
5     2015  2015-16     1        6       Michigan State       5.333333
6     2015  2015-16     1        7               Auburn      13.500000
7     2015  2015-16     1        8        Florida State      10.600000
8     2015  2015-16     1        9              Georgia      12.750000
9     2015  2015-16     1       10  Southern California      16.777778
10    2015  2015-16     1       11           Notre Dame       9.066667
11    2015  2015-16     1       12              Clemson       5.933333
12    2015  2015-16     1       13      Louisiana State      10.785714
13    2015  2015-16     1       14                 UCLA      16.909091
14    2015  2015-16     1       15          Mississippi      15.071429
15    2015  2015-16     1       16        Arizona State      16.000000
16    2015  2015-16     1       17         Georgia Tech      17.250000
17    2015  2015-16     1       18            Wisconsin      21.375000
18    2015  2015-16     1       19             Oklahoma      12.066667
19    2015  2015-16     1       20             Arkansas      19.000000
20    2015  2015-16     1       21             Stanford      13.307692
21    2015  2015-16     1       22              Arizona      19.250000
22    2015  2015-16     1       23             Missouri      21.750000
23    2015  2015-16     1       24          Boise State      22.500000
24    2015  2015-16     1       25            Tennessee      23.666667
25    2015  2015-16     2        1                 Ohio       2.266667
26    2015  2015-16     2        2              Alabama       5.733333
27    2015  2015-16     2        3      Texas Christian       5.866667
28    2015  2015-16     2        4               Baylor       5.466667
29    2015  2015-16     2        5               Oregon      14.555556
...    ...      ...   ...      ...                  ...            ...
1471  2018  2018-19    14       21         Northwestern      21.333333
1472  2018  2018-19    14       22          Boise State      22.400000
1473  2018  2018-19    14       23           Iowa State      22.500000
1474  2018  2018-19    14       24             Missouri      23.500000
1475  2018  2018-19    14       25         Fresno State      21.800000
1476  2018  2018-19    15        1              Alabama       1.000000
1477  2018  2018-19    15        2              Clemson       2.333333
1478  2018  2018-19    15        3           Notre Dame       5.333333
1479  2018  2018-19    15        4             Oklahoma       6.200000
1480  2018  2018-19    15        5              Georgia       4.066667
1481  2018  2018-19    15        6                 Ohio       5.400000
1482  2018  2018-19    15        7             Michigan      11.066667
1483  2018  2018-19    15        8      Central Florida      12.666667
1484  2018  2018-19    15        9           Washington      12.400000
1485  2018  2018-19    15       10              Florida      14.700000
1486  2018  2018-19    15       11      Louisiana State       9.600000
1487  2018  2018-19    15       12           Penn State      12.266667
1488  2018  2018-19    15       13     Washington State      12.500000
1489  2018  2018-19    15       14             Kentucky      15.909091
1490  2018  2018-19    15       15                Texas      15.000000
1491  2018  2018-19    15       16        West Virginia      12.333333
1492  2018  2018-19    15       17                 Utah      19.142857
1493  2018  2018-19    15       18    Mississippi State      18.181818
1494  2018  2018-19    15       19            Texas A&M      19.500000
1495  2018  2018-19    15       20             Syracuse      18.000000
1496  2018  2018-19    15       21         Fresno State      21.800000
1497  2018  2018-19    15       22         Northwestern      21.333333
1498  2018  2018-19    15       23             Missouri      23.500000
1499  2018  2018-19    15       24           Iowa State      22.500000
1500  2018  2018-19    15       25          Boise State      22.400000

[1501 rows x 6 columns]

In [63]:
df_to_merge = df[["Season", "Ranking", "College", "SeasonRanking"]]
final_merged = pd.merge(left=game_data, right=df_to_merge,how='left', left_on=['School', 'Season'], right_on=['College', 'Season'])
del final_merged['College']
final_merged = final_merged.fillna(-1).drop_duplicates()
final_merged

,School,Opponent,Date,Season,AtHome,NeutralLocation,Score,OppScore,Total,Outcome,...,XPPercent,FGM,FGA,FGPercent,KickPts,Fum,Int,TotalTO,Ranking,SeasonRanking
0,Georgia State,Charlotte,2015-09-04,2015-16,1,0,20,23,43,L,...,100.0,2,3,66.7,8,2,1,3,-1.0,-1.000000
1,Oregon State,Weber State,2015-09-04,2015-16,1,0,26,7,33,W,...,100.0,4,4,100.0,14,0,1,1,-1.0,-1.000000
2,Syracuse,Rhode Island,2015-09-04,2015-16,1,0,47,0,47,W,...,100.0,1,2,50.0,9,0,1,1,-1.0,-1.000000
3,Western Michigan,Michigan State,2015-09-04,2015-16,1,0,24,37,61,L,...,100.0,1,2,50.0,6,0,2,2,-1.0,-1.000000
4,Central Michigan,Oklahoma State,2015-09-03,2015-16,1,0,13,24,37,L,...,100.0,2,2,100.0,7,0,1,1,-1.0,-1.000000
5,Fresno State,Abilene Christian,2015-09-03,2015-16,1,0,34,13,47,W,...,100.0,2,3,66.7,10,1,2,3,-1.0,-1.000000
6,Hawaii,Colorado,2015-09-03,2015-16,1,0,28,20,48,W,...,100.0,2,2,100.0,8,0,2,2,-1.0,-1.000000
7,Idaho,Ohio,2015-09-03,2015-16,1,0,28,45,73,L,...,100.0,2,2,100.0,8,1,2,3,-1.0,-1.000000
8,Minnesota,Texas Christian,2015-09-03,2015-16,1,0,17,23,40,L,...,100.0,1,1,100.0,5,2,0,2,-1.0,-1.000000
9,San Jose State,New Hampshire,2015-09-03,2015-16,1,0,43,13,56,W,...,66.7,1,2,50.0,7,0,0,0,-1.0,-1.000000
10,Central Florida,Florida International,2015-09-03,2015-16,1,0,14,15,29,L,...,100.0,0,1,0.0,2,0,0,0,-1.0,-1.000000
11,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,25.0,15.857143
12,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,21.0,15.857143
13,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,17.0,15.857143
14,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,12.0,15.857143
15,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,7.0,15.857143
18,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,14.0,15.857143
20,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,13.0,15.857143
21,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,18.0,15.857143
23,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,20.0,15.857143
24,Utah,Michigan,2015-09-03,2015-16,1,0,24,17,41,W,...,100.0,1,3,33.3,6,0,1,1,22.0,15.857143
25,Utah State,Southern Utah,2015-09-03,2015-16,1,0,12,9,21,W,...,100.0,1,1,100.0,4,0,1,1,-1.0,-1.000000
26,Wake Forest,Elon,2015-09-03,2015-16,1,0,41,3,44,W,...,100.0,2,3,66.7,11,0,0,0,-1.0,-1.000000
27,West Virginia,Liberty,2015-09-12,2015-16,1,0,41,17,58,W,...,100.0,2,3,66.7,11,0,0,0,21.0,21.000000
28,Wisconsin,Miami (OH),2015-09-12,2015-16,1,0,58,0,58,W,...,100.0,3,3,100.0,16,0,1,1,18.0,21.375000
29,Wisconsin,Miami (OH),2015-09-12,2015-16,1,0,58,0,58,W,...,100.0,3,3,100.0,16,0,1,1,24.0,21.375000
30,Wisconsin,Miami (OH),2015-09-12,2015-16,1,0,58,0,58,W,...,100.0,3,3,100.0,16,0,1,1,23.0,21.375000
31,Wisconsin,Miami (OH),2015-09-12,2015-16,1,0,58,0,58,W,...,100.0,3,3,100.0,16,0,1,1,21.0,21.375000
33,Wisconsin,Miami (OH),2015-09-12,2015-16,1,0,58,0,58,W,...,100.0,3,3,100.0,16,0,1,1,22.0,21.375000
34,Wisconsin,Miami (OH),2015-09-12,2015-16,1,0,58,0,58,W,...,100.0,3,3,100.0,16,0,1,1,20.0,21.375000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17844,Ball State,Eastern Michigan,2019-10-12,2019-20,0,0,29,23,52,W,...,100.0,0,1,0.0,3,1,0,1,-1.0,-1.000000
17845,Brigham Young,South Florida,2019-10-12,2019-20,0,0,23,27,50,L,...,100.0,3,4,75.0,11,1,0,1,-1.0,-1.000000
17846,Charlotte,Florida International,2019-10-12,2019-20,0,0,23,48,71,L,...,66.7,1,1,100.0,5,1,0,1,-1.0,-1.000000
17847,Cincinnati,Houston,2019-10-12,2019-20,0,0,38,23,61,W,...,100.0,1,2,50.0,8,0,1,1,-1.0,-1.000000
17848,Fresno State,Air Force,2019-10-12,2019-20,0,0,24,43,67,L,...,100.0,1,1,100.0,6,0,1,1,-1.0,-1.000000
17849,Georgia State,Coastal Carolina,2019-10-12,2019-20,0,0,31,21,52,W,...,100.0,1,2,50.0,7,0,1,1,-1.0,-1.000000
17850,Georgia Tech,Duke,2019-10-12,2019-20,0,0,23,41,64,L,...,100.0,1,1,100.0,5,0,0,0,-1.0,-1.000000
17851,Iowa State,West Virginia,2019-10-12,2019-20,0,0,38,14,52,W,...,100.0,1,1,100.0,8,0,1,1,-1.0,-1.000000
17852,Kent State,Akron,2019-10-12,2019-20,0,0,26,3,29,W,...,100.0,4,4,100.0,14,0,0,0,-1.0,-1.000000
17853,Louisville,Wake Forest,2019-10-12,2019-20,0,0,62,59,121,W,...,100.0,2,2,100.0,14,1,1,2,-1.0,-1.000000
17854,Miami (OH),Western Michigan,2019-10-12,2019-20,0,0,16,38,54,L,...,100.0,3,4,75.0,10,0,3,3,-1.0,-1.000000
17855,Michigan,Illinois,2019-10-12,2019-20,0,0,42,25,67,W,...,100.0,0,1,0.0,6,2,0,2,-1.0,-1.000000
17856,Middle Tennessee State,Florida Atlantic,2019-10-12,2019-20,0,0,13,28,41,L,...,50.0,0,1,0.0,1,0,3,3,-1.0,-1.000000
17857,Mississippi State,Tennessee,2019-10-12,2019-20,0,0,10,20,30,L,...,100.0,1,2,50.0,4,0,3,3,-1.0,-1.000000
17858,Navy,Tulsa,2019-10-12,2019-20,0,0,45,17,62,W,...,100.0,1,1,100.0,9,1,0,1,-1.0,-1.000000
17859,North Texas,Southern Mississippi,2019-10-12,2019-20,0,0,27,45,72,L,...,75.0,0,1,0.0,3,0,2,2,-1.0,-1.000000
17860,Northern Illinois,Ohio,2019-10-12,2019-20,0,0,39,36,75,W,...,100.0,2,4,50.0,9,0,1,1,-1.0,-1.000000
17861,Oklahoma,Texas,2019-10-12,2019-20,0,1,34,27,61,W,...,100.0,2,2,100.0,10,1,1,2,-1.0,-1.000000
17862,Old Dominion,Marshall,2019-10-12,2019-20,0,0,17,31,48,L,...,100.0,1,1,100.0,5,0,0,0,-1.0,-1.000000
17863,Penn State,Iowa,2019-10-12,2019-20,0,0,17,12,29,W,...,100.0,1,1,100.0,5,0,0,0,-1.0,-1.000000
17864,San Jose State,Nevada,2019-10-12,2019-20,0,0,38,41,79,L,...,100.0,1,1,100.0,8,1,1,2,-1.0,-1.000000
17865,South Carolina,Georgia,2019-10-12,2019-20,0,0,20,17,37,W,...,100.0,2,4,50.0,8,0,0,0,-1.0,-1.000000
17866,Texas Tech,Baylor,2019-10-12,2019-20,0,0,30,33,63,L,...,100.0,3,3,100.0,12,1,2,3,-1.0,-1.000000
17867,Toledo,Bowling Green State,2019-10-12,2019-20,0,0,7,20,27,L,...,100.0,0,2,0.0,1,1,1,2,-1.0,-1.000000
17868,Alabama-Birmingham,Texas-San Antonio,2019-10-12,2019-20,0,0,33,14,47,W,...,100.0,4,4,100.0,15,1,1,2,-1.0,-1.000000
17869,Nevada-Las Vegas,Vanderbilt,2019-10-12,2019-20,0,0,34,10,44,W,...,100.0,2,2,100.0,10,1,0,1,-1.0,-1.000000
17870,Southern California,Notre Dame,2019-10-12,2019-20,0,0,27,30,57,L,...,100.0,2,2,100.0,9,0,0,0,-1.0,-1.000000
17871,Utah,Oregon State,2019-10-12,2019-20,0,0,52,7,59,W,...,100.0,1,1,100.0,10,1,0,1,-1.0,-1.000000
17872,Washington,Arizona,2019-10-12,2019-20,0,0,51,27,78,W,...,100.0,3,3,100.0,15,1,0,1,-1.0,-1.000000
17873,Washington State,Arizona State,2019-10-12,2019-20,0,0,34,38,72,L,...,100.0,2,2,100.0,10,0,0,0,-1.0,-1.000000

In [38]:
final_merged[["SeasonRanking"]].drop_duplicates().sort_values(["SeasonRanking"])

      SeasonRanking
2887       1.000000
5150       1.466667
319        2.266667
7044       2.333333
2519       2.866667
4891       3.333333
2424       3.400000
7074       4.066667
2600       4.533333
277        5.333333
7122       5.400000
590        5.466667
569        5.733333
813        5.866667
212        5.933333
7137       6.200000
4845       6.333333
4624       6.733333
2475       6.933333
4776       7.066667
5462       8.250000
136        9.066667
2730       9.285714
7463       9.600000
5171       9.866667
103       10.000000
2324      10.200000
79        10.600000
7604      10.714286
400       10.785714
...             ...
693       20.166667
7101      20.600000
4949      20.625000
6952      20.666667
4799      20.750000
27        21.000000
2469      21.166667
522       21.250000
4812      21.333333
28        21.375000
199       21.500000
5075      21.600000
7628      21.666667
435       21.750000
7069      21.800000
60        22.000000
7799      22.250000
7174      22.400000
202       22.500000
4729      22.666667
179       22.714286
2490      22.750000
292       22.800000
2420      23.000000
7099      23.500000
383       23.666667
175       24.000000
2447      24.500000
4882      25.000000
0               NaN

[131 rows x 1 columns]